version: '3'

services:

  web:
    build:
      context: ./web/
    ports:
      - "5000:5000"
    volumes:
      - ./web/app/:/usr/src/app/
    command: python app.py
    restart: unless-stopped

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
