version: '3'

services:

  web:
    build: ./web/
    image: interview_web:v1
    stop_grace_period: 10s
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      update_config:
        delay: 10s
    command: python app.py
    restart: unless-stopped

  nginx:
    build: ./nginx/
    image: interview_nginx:v1
    restart: always
    ports:
      - "80:80"
